---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: receptor

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: receptor-conf
    files:
      - ./conf/node04.yml

images:
  - name: quay.io/ansible/receptor
    newTag: v1.3.0.dev2

resources:
  - ./manifests/namespace.yml
  - ./manifests/serviceaccount.yml
  - ./manifests/role.yml
  - ./manifests/rolebinding.yml
  - ./manifests/node04.yml
