apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: receptor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: receptor
subjects:
  - kind: ServiceAccount
    name: receptor
