apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: receptor
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods/attach
    verbs:
      - create
